### ISSUE TITLE
Address warning when running `yarn test` in @ez/vue

### ISSUE THREAD

**Issue by marrouchi** [Hexastack/eazychart#1]
There's a warning that shows up when running `yarn test:vue`. The onResize not being passed, while it should be optional.
```
Console
@ez/vue:     console.error ../../node_modules/vue/dist/vue.runtime.common.dev.js:571
@ez/vue:       [Vue warn]: Invalid handler for event "resize": got undefined
@ez/vue:       
@ez/vue:       found in
@ez/vue:       
@ez/vue:       ---> <Chart>
@ez/vue:              <BarChart>
@ez/vue:                <Root>
```

**Comment by AlanLes** [comment]
Hello, can I take this one? ;) Can you please assign me to this?

**Comment by AlanLes** [comment]
I've got an error when running `yarn test:vue`, do you know why is that? I use node v16.14.2.
<img width="911" alt="image" src="https://user-images.githubusercontent.com/13744352/193418513-35bc9b2c-d13c-4cae-910f-c24c11b13d17.png">

**Comment by marrouchi** [comment]
@AlanLes , Yes for sure, I just assigned it to you. Can you run the following ?
```
cd packages/ez-vue/
yarn test
```

**Comment by marrouchi** [comment]
Ah you'll need to install the vue-cli-service globally ... sorry my bad, could you open an issue for this ?
```
npm install -g @vue/cli
# OR
yarn global add @vue/cli
```

**Comment by AlanLes** [comment]
@marrouchi I created a bug, but it seems like it's not the case 🤔 
I've already installed the `@vue/cli` globally, and the issue still exists 🤔 seems like there is missing more... 

after `npm i -g @vue/cli` we have:
```bash
> eazychart-vue@0.1.16-alpha.0 test
> vue-cli-service test:unit

sh: vue-cli-service: command not found
``` 


Then, after `npm i -g @vue/cli-service` when running `npm run test` have:

```bash

> eazychart-vue@0.1.16-alpha.0 test
> vue-cli-service test:unit

node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '@vue/cli-plugin-babel'
Require stack:
```

and then after `npm i -g @vue/cli-plugin-babel`, when running `npm run test` another one...

```bash

> eazychart-vue@0.1.16-alpha.0 test
> vue-cli-service test:unit

node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '@vue/cli-plugin-eslint'
Require stack:
```


I feel like it's never going to end 😅  there must be another way 😖

When running `npm install` in the `packages/ez-vue` directory, why there's this error?
```bash
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/eazychart-dev - Not found
npm ERR! 404
npm ERR! 404  'eazychart-dev@^0.1.15-alpha.0' is not in this registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

**Comment by marrouchi** [comment]
@AlanLes did you run the command `yarn setup` after you cloned the project ?

**Comment by AlanLes** [comment]
Ah, good point, I missed that, thanks!
