### ISSUE TITLE
:bug: [BUG] - @eazychart-react - Data does not get sorted in RadialChart 

### ISSUE THREAD

**Issue by IlyesBenAmara** [Hexastack/eazychart#14]
### Description
`RadialChart` is not behaving correctly. The outer circular bar (arc) should display the max value of the data and therefore the bigger arc. This could be resulted from the `sortValue` function that is not working accordingly. The radial chart is a chart that has circular arcs that are displaying values from a giving column of data. 

### Reproduction steps
1. Create a React project
2. Install the eazychart-react and the eazychart-css packages.
```bash
npm install eazychart-react  eazychart-css
```
3. Add the radial chart to your app component
### Code
```typescript
import { RadialChart } from 'eazychart-react';
import 'eazychart-css';
const App = () => {
  return (
    <div className="App">
      <RadialChart
        colors={['#FF595E', '#FFCA3A', '#8AC926', '#1982C4', '#6A4C93']}
        arc={{ spacing: 0.3 }}
        domainKey={'value'}
        rawData={[
          { label: 'Alpha', value: 30 },
          { label: 'Gamma', value: 20 },
          { label: 'Beta', value: 10 },
          { label: 'Teta', value: 40 },
          { label: 'Zeta', value: 50 },
        ]}
      />
    </div>
  );
};

export default App;

```
### Screenshots 
![image](https://user-images.githubusercontent.com/22627035/193608673-b26f2533-884b-468c-967f-8cd05d2301dc.png)

**Comment by Rishabh044** [comment]
Could you please elaborate more @IlyesBenAmara ?? Also please let me know what packages would I have to install if I want to reproduce the following. Thanks in Advance!

**Comment by IlyesBenAmara** [comment]
- Every circular chart component (`Pie, IrregularArcs, Arcs`) have a function called `sortValues` that will be passed to the scale function (the scale function is needed to transform the data into path data). Simply adding a sort function to this component doesn't give the suited behavior. 
you need to investigate on why the sort function does not work in these components. 
- the components are located in the `packages/ez-react/components` and `packages/ez-vue/components` (so you need to make it work on both Vue and React.)

**Comment by IlyesBenAmara** [comment]
Let us know if you want to work on this issue so that we can assign it to you ;)

**Comment by Rishabh044** [comment]
Sure, I would like to work on the following issue. Please assign it to me. :)
