### ISSUE TITLE
🐛 [BUG] - @eazychart-[vue]- missing global dependency package @vue/cli

### ISSUE THREAD

**Issue by AlanLes** [Hexastack/eazychart#36]
### Description

When one wants to run vue-tests, one needs to have @vue/cli installed globally. 

### Reproduction steps

Given having no @vue/cli installed globally try to:
1. Go to `cd packages/ez-vue`
2. Run `yarn test` or `npm run test`

The result is 

```bash
> eazychart-vue@0.1.16-alpha.0 test
> vue-cli-service test:unit

sh: vue-cli-service: command not found
```

### Screenshots

<img width="368" alt="image" src="https://user-images.githubusercontent.com/13744352/193421680-8134f3f1-834c-42e9-b72a-a7a967428251.png">

### OS

Mac

**Comment by marrouchi** [comment]
@AlanLes  I think we should probably add a line in the readme file, under the "Contribute" section to state that one needs to install it globally. Or we should add it as a dev dependency for the package "ez-vue". WDYT ?

**Comment by AlanLes** [comment]
I guess we shouldn't obligate anybody to install packages globally; therefore, I'm 100% for the alternative of adding additional devDependency for the package `ez-vue` :)

**Comment by marrouchi** [comment]
@AlanLes vue cli appears to be already in the devDependencies, https://github.com/Hexastack/eazychart/blob/79428948bcffd02bb6d1710f5cefa94291de4006/packages/ez-vue/package.json#L78

Could it be that happened because you didn't run `yarn setup` ?

**Comment by AlanLes** [comment]
Yep, I guess it must be that. I believe we may close this Issue already.  😇
