### ISSUE TITLE
🤔 [ISSUE] - @eazychart-[react & vue] - Points not centered in the LineColumnChart

### ISSUE THREAD

**Issue by marrouchi** [Hexastack/eazychart#43]
### Description

It's seems that the points of the line are not centered in the columns. (See screenshot)

### Reproduction steps

1. Run `yarn storybook`
2. Click on 'Line Column' under 'Column Chart'

### Screenshots

![image](https://user-images.githubusercontent.com/1827776/194028893-fefaa735-8530-4a68-b3e3-1d4d793905c6.png)

**Comment by marrouchi** [comment]
Done !

**Comment by i-m-karanagarwal** [comment]
Hy @marrouchi, I couldn,t install the eazychart on my local system as it couldn.t find the specified files.
![Screenshot from 2022-10-08 12-00-52](https://user-images.githubusercontent.com/77572300/194693391-dfa7c30f-3703-4d62-9051-d901433c23b4.png)

Please Help me out.

**Comment by marrouchi** [comment]
@i-m-karanagarwal  Hi, did you clone the project with the command this way ? 
`git clone https://github.com/Hexastack/eazychart.git`

**Comment by i-m-karanagarwal** [comment]
Yes the same command. I followed the instruction given in [https://github.com/Hexastack/eazychart#installation-1](url).

**Comment by marrouchi** [comment]
Those instructions are for developers who are going to use the library. But you want to contribute in it, right ? So please refer to the contributer section in the main README.md file, fork this project on github and then clone it locally. You can follow this document to learn how to contribute on github : https://docs.github.com/en/get-started/quickstart/contributing-to-projects

**Comment by i-m-karanagarwal** [comment]
You are referring to this one installation guide right?
![image](https://user-images.githubusercontent.com/77572300/194695594-3268fa1a-2a95-4ce6-bf14-9cf67c2f14a9.png)

As it is under the contribution guide, I followed the same instructions.

**Comment by marrouchi** [comment]
Yes, did you install yarn globally ? also could you do `ls` command into the folder ?

**Comment by i-m-karanagarwal** [comment]
Yes Sure
![Screenshot from 2022-10-08 13-41-06](https://user-images.githubusercontent.com/77572300/194697426-93519a69-e48d-4ced-ab72-c1fc14c9a2e5.png)

**Comment by marrouchi** [comment]
Can you please specify your node and yarn version ?
```
yarn -v
node -v
```

**Comment by i-m-karanagarwal** [comment]
Yes Sure
![image](https://user-images.githubusercontent.com/77572300/194697806-a89f1a6b-0338-42af-8bb0-82756689819b.png)

**Comment by marrouchi** [comment]
Can you switch to node v16 using NVM and retest ? 
Node : v16.13.0
Yarn : 1.21.1

**Comment by marrouchi** [comment]
It seems to be an issue with Yarn https://github.com/yarnpkg/yarn/issues/3708

Please use the versions I specified in the previous message.

**Comment by i-m-karanagarwal** [comment]
Thank You, It is working now.
Adding the required version in the contribution docs would be a great help.

**Comment by marrouchi** [comment]
Can you open a new issue for this please ?

**Comment by i-m-karanagarwal** [comment]
I think this can be included with issue #59  .
