### ISSUE TITLE
🐛 [BUG] - @eazychart-[react & vue] - global verticalAxis Tick Rotation with enabled RTL

### ISSUE THREAD

**Issue by yassinedorbozgithub** [Hexastack/eazychart#53]
### Description

I find that for the Area Chart, Bar Chart, Line Chart, Scatter Chart when we enable the RTL the Tick situated in the verticalAxis do an extra rotation.

### Reproduction steps

```bash
1. yarn storybook
2. Open one of those charts Area Chart, Bar Chart, Line Chart, Scatter Chart
3. Enable the RTL and observe the verticalAxis Tick Rotation
```

### Screenshots
- Area Chart 
RTL=false
![image](https://user-images.githubusercontent.com/95612053/194499420-46cf6a7a-1d98-4150-818f-697bd9220e90.png)
RTL=true with the bug
![image](https://user-images.githubusercontent.com/95612053/194499570-25680e94-a43e-4857-8267-5f6d81c5900c.png)
- Bar Chart
RTL=false
![image](https://user-images.githubusercontent.com/95612053/194499733-dcff30bc-8ea9-4bda-994c-63ca9fe9e22e.png)
RTL=true with the bug
![image](https://user-images.githubusercontent.com/95612053/194499857-30fea48b-7399-473a-bb1a-9e0bcaacb5ea.png)
- Line Chart
RTL=false
![image](https://user-images.githubusercontent.com/95612053/194499942-bba816f5-a94d-4a3c-b2d1-c887fdfe0265.png)
RTL=true with the bug
![image](https://user-images.githubusercontent.com/95612053/194500082-17630211-2e1b-4096-9042-df07ac4105e9.png)
- Scatter Chart
RTL=false
![image](https://user-images.githubusercontent.com/95612053/194500151-ec76b488-05e5-449e-97a4-a02ef152dd5e.png)
RTL=true with the bug
![image](https://user-images.githubusercontent.com/95612053/194500362-b828e20b-d72f-4493-99a4-1e51842062db.png)

### Browsers

Chrome

### OS

Linux

**Comment by marrouchi** [comment]
@yassinedorbozgithub On react it seems to be working fine, but not in Vue. Can you re-check please?

**Comment by yassinedorbozgithub** [comment]
Hey @marrouchi after the test the i find that the update is working like expected (react & vue).
