### ISSUE TITLE
🐛 [BUG] - @eazychart-[react & vue] -  AreaChart coloration discontinuity when swapAxis is true 

### ISSUE THREAD

**Issue by yassinedorbozgithub** [Hexastack/eazychart#55]
### Description

I find that for the Area Chart has a discontinuity when swapAxis is true.

### Reproduction steps

```bash
1. yarn storybook
2. Select Area Chart
3. Enable the swapAxis and observe the chart coloration discontinuity
```

### Screenshots
- Area Chart 
swapAxis=true with the bug
![image](https://user-images.githubusercontent.com/95612053/194522802-1dacc0a6-c05d-428c-9d64-d5f155c554bc.png)
swapAxis=false
![image](https://user-images.githubusercontent.com/95612053/194522963-c6cf68bb-b9f1-4853-afa5-f9d6a2e45c3f.png)

### Browsers

Chrome

### OS

Linux

**Comment by marrouchi** [comment]
@yassinedorbozgithub In the current PR I'm working on, I removed the swapAxis prop from all charts. This because we can simply swap using yAxis and xAxis props.
